# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_data_warehouse_project'
version: '1.0.0'
profile: 'sql_data_warehouse_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"] # <--- Ensure this is now commented out or removed if you delete the macro folder
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_data_warehouse_project:
    +materialized: view # Default materialization for the project

    staging:
      +database: main   # <--- EXPLICITLY set the Unity Catalog
      +schema: silver   # <--- EXPLICITLY set the schema within that catalog
    marts:
      +database: main   # <--- EXPLICITLY set the Unity Catalog
      +schema: gold     # <--- EXPLICITLY set the schema within that catalog
      # +materialized: table # Optional: uncomment if you want marts to be tables instead of views